public enum EnemyType
{
    Cell = 0,
    CellTwo = 1,
    CellFour = 2,
    Eye_Shooter = 3,
    Puff = 4,
    Root = 5,
    CrystalMeat = 6,
    Volatile = 7,
    Jelly = 14,
    Eye_Crystal = 17,
    JellyShield = 18,
    JellyBulb = 19,
    PlantFlower = 20,
    RootTeleport = 21,
    Tripleye = 22,
    CrystalBall = 23,
    Camo = 24,

    BossInfection = 8,
    BossShooter = 9,
    BossPlant = 10,
    BossRoot = 11,
    BossCrystalEyes = 12,
    BossAngler = 13,
    BossJelly = 15,
    BossMaw = 16,
}